# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgb_image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rgb_image.proto',
  package='ai_powered_visual_inspection_for_manifacturing',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0frgb_image.proto\x12.ai_powered_visual_inspection_for_manifacturing\"U\n\tRGB_image\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"q\n\nRGB_images\x12\x18\n\x10number_of_images\x18\x01 \x01(\x05\x12I\n\x06images\x18\x02 \x03(\x0b\x32\x39.ai_powered_visual_inspection_for_manifacturing.RGB_image')
)




_RGB_IMAGE = _descriptor.Descriptor(
  name='RGB_image',
  full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.depth', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_image.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=152,
)


_RGB_IMAGES = _descriptor.Descriptor(
  name='RGB_images',
  full_name='ai_powered_visual_inspection_for_manifacturing.RGB_images',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_images', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_images.number_of_images', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ai_powered_visual_inspection_for_manifacturing.RGB_images.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=267,
)

_RGB_IMAGES.fields_by_name['images'].message_type = _RGB_IMAGE
DESCRIPTOR.message_types_by_name['RGB_image'] = _RGB_IMAGE
DESCRIPTOR.message_types_by_name['RGB_images'] = _RGB_IMAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RGB_image = _reflection.GeneratedProtocolMessageType('RGB_image', (_message.Message,), dict(
  DESCRIPTOR = _RGB_IMAGE,
  __module__ = 'rgb_image_pb2'
  # @@protoc_insertion_point(class_scope:ai_powered_visual_inspection_for_manifacturing.RGB_image)
  ))
_sym_db.RegisterMessage(RGB_image)

RGB_images = _reflection.GeneratedProtocolMessageType('RGB_images', (_message.Message,), dict(
  DESCRIPTOR = _RGB_IMAGES,
  __module__ = 'rgb_image_pb2'
  # @@protoc_insertion_point(class_scope:ai_powered_visual_inspection_for_manifacturing.RGB_images)
  ))
_sym_db.RegisterMessage(RGB_images)


# @@protoc_insertion_point(module_scope)
